// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idzauxvceeaxyqrvmxoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkemF1eHZjZWVheHlxcnZteG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODYzNjcsImV4cCI6MjA2OTc2MjM2N30.Od2n9ivUcF45Ik8BNfKV6fI2oSRObZ_eHanYXAGN6So";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});